### ISSUE TITLE
boost struct is_copy_constructible fails to compile with VS 2017 15.5.2

### ISSUE THREAD

**Issue by jmp75** [jmp75/senaps-cpp#4]
Compiling SenapsCPP with VS 2017 15.5.2
```
c:\src\github\vcpkg\installed\x64-windows\include\boost/move/detail/type_traits.hpp(757): error C2760: syntax error: unexpected token ')', expected 'expression'
```
I have no idea how this comes to be needed and compiled. Why not use the std:: versions anyway - it is 2017.
At any rate did not manage to find a workaround yet.

**Comment by braneof** [comment]
@jmp75 Did you ever figure this out? Just ran into it when I switched the C++ Language Standard to ISO C++ Latest Draft Standard (/std::c++latest).
